Repository abid7955/WebDevProject, pull requests merged in 2022-10, with the labels that each got.

#1 Create Hello.py
  Hello.py
Labels: hacktoberfest, hacktoberfest2022

#2 Create roundoff.py
  roundoff.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#3 Create Rana.py
  Rana.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#5 School.html
  School.html
Labels: hacktoberfest-accepted

#6 Create factorial.swift
  factorial.swift
Labels: hacktoberfest-accepted

#7 Wrote a python code for number guessing game
  NumberGuessingGame.py
Labels: hacktoberfest-accepted

#8 convert decimal number to binary without using inbuilt function in python
  DecimalToBinary.py
Labels: hacktoberfest-accepted

#9 code for making heart in python
  heart.py
Labels: hacktoberfest-accepted

#10 Hacktoberfest 2022
  recursion.cpp
Labels: hacktoberfest-accepted

#11 Create stack.cpp
  stack.cpp
Labels: hacktoberfest-accepted
